Django4Full-Stack course/DJANGO/section10_rev1/venv1/my_project/my_app/urls.py
from django.urls import path
from . import views

# register the app namespace
# URL NAMES
app_name = 'my_app'


urlpatterns = [
    path('', views.example_view, name='example'),
    path('variables/', views.variables_view),
    path('new_variables/', views.new_variable_view, name='new_variable'),
]

Django4Full-Stack course/DJANGO/section10_rev1/venv1/my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),

]


handler404 = 'my_project.views.custm_page_not_found_view'

Django4Full-Stack course/DJANGO/section10_rev1/venv1/my_project/my_app/views.py
from django.shortcuts import render

# Create your views here.


def example_view(request):
    return render(request, 'my_app/example.html')


def variables_view(request):
    my_var = {'first_name': 'artur', 'last_name': 'Ito', 'some_list': [
        5, 4, 3], 'some_dict': {'inside_key': 'inside_value'}, 'user_logged_in': True}
    return render(request, 'my_app/variables.html', context=my_var)


def new_variable_view(request):
    return render(request, 'my_app/new_variables.html')

Django4Full-Stack course/DJANGO/section10_rev1/venv1/my_project/my_project/views.py
from django.shortcuts import render

def custm_page_not_found_view(request, exception):
    return render(request, 'error404.html', status=404)

Django4Full-Stack course/DJANGO/section10_rev1/venv1/my_project/my_app/templates/my_app/example.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="icon" href="./favicon.ico" type="image/x-icon" />
  </head>
  <body>
    <h1>Example html connected template</h1>
    <h1>
      <a href="new_variables/">GO TO NEW Variable</a> <br />
      <a href="{% url 'my_app:new_variable' %}">GO TO NEW Variable different</a>
      <br />
    </h1>
  </body>
</html>

Django4Full-Stack course/DJANGO/section10_rev1/venv1/my_project/my_app/templates/my_app/new_variables.html
{% extends 'base.html' %} {% load static %}

<body>
  <br />

  {% comment %} Inheritance - repetetive block of code {% endcomment %}
  <h3>Inheritance - repetetive block:</h3>

  {% block content %}
  <h2>This is inside the block in new variables.html</h2>
  <img src="{% static 'my_app/photo.png' %}" alt="my image" />
  {% endblock %}
</body>

Django4Full-Stack course/DJANGO/section10_rev1/venv1/my_project/my_app/templates/my_app/variables.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Variable Document</title>
    <link rel="icon" href="./favicon.ico" type="image/x-icon" />
  </head>
  <body>
    <h1>VARIABLES.html</h1>

    {% if user_logged_in %}
    <h1>Welcome back, you're logged in</h1>
    {% endif %}

    <h2>
      FILTER: {{first_name}} | upper is very famous in Poland, because of his
      last name: {{last_name}} <br /><br />

      TAGS: He was doing very good in schoold, his grades were mainly: <br />
      <ul>
        {% for item in some_list %} {% if item == 4 %}
        <li>four</li>
        {% else %}
        <li>{{item}}</li>
        {% endif %} {% endfor %}
      </ul>

      <ul>
        {% for k,v in some_dict.items %}
        <li>{{k}} - {{v}}</li>
        {% endfor %}
      </ul>
    </h2>
    <h3>{{some_dict.inside_key}}</h3>
    FILTERS INFO {# this is single line comment, below you see multiline s#}
    <br />
    {% comment %}
    <p>
      Filters - django templates built-in (you can also create your own)
      functions that transforms look by using them - for example: {name} shows:
      Rosalind, but {name} | upper would show: ROSALIND
    </p>
    {% endcomment %} TAGS INFO {% comment %}
    <p>Tags - additional logic provided during rendering process</p>
    {% endcomment %}
  </body>
</html>