Django4Full-Stack course/DJANGO/section12_rev1/my_site/my_app/urls.py
from django.urls import path
from . import views

app_name = 'my_app'

urlpatterns = [
    path('list/', views.list_view, name='list'),
    path('add/', views.add_view, name='add'),
    path('delete/', views.delete_view, name='delete'),
]

Django4Full-Stack course/DJANGO/section12_rev1/my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include("my_app.urls"))
]

Django4Full-Stack course/DJANGO/section12_rev1/my_site/my_app/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    #pk
    brand = models.CharField(max_length=50)
    year = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.pk} | {self.brand} - {self.year}"

Django4Full-Stack course/DJANGO/section12_rev1/my_site/my_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models

# Create your views here.
def list_view(request):
    all_cars = models.Car.objects.all()
    context = {"all_cars":all_cars}
    return render(request, 'my_app/list.html', context=context)

def add_view(request):
    if request.POST:
        brand = request.POST['brand']
        year = int(request.POST['year'])
        models.Car.objects.create(brand=brand,year=year)
        return redirect(reverse('my_app:list'))
    else:
        return render(request, 'my_app/add.html')

def delete_view(request):
    if request.POST:
        pk = request.POST['pk']
        try:
            models.Car.objects.get(pk=pk).delete()
            return redirect(reverse('my_app:list'))
        except:
            print("There's no car with such a PK")
            return redirect(reverse('my_app:list'))
    else:
        return render(request, 'my_app/delete.html') 

Django4Full-Stack course/DJANGO/section12_rev1/my_site/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>base</title>
    <link rel="icon" href="./favicon.ico" type="image/x-icon" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <!--NAVBAR-->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'my_app:list'%}">LIST</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'my_app:add'%}">ADD</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'my_app:delete'%}">DELETE</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %} {% endblock %}
  </body>
</html>