Django4Full-Stack course/DJANGO/section12/django_project/car_rental/urls.py
from django.urls import path
from . import views

app_name = 'car_rental'

urlpatterns = [
    path('list/', views.list, name='list'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
]

Django4Full-Stack course/DJANGO/section12/django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', include('car_rental.urls')),
]

Django4Full-Stack course/DJANGO/section12/django_project/car_rental/models.py
from django.db import models

# Create your models here.


class Car(models.Model):
    # pk
    brand = models.CharField(max_length=30)
    year = models.IntegerField()

    def __str__(self):
        return f"Car is {self.brand} {self.year}"

Django4Full-Stack course/DJANGO/section12/django_project/car_rental/views.py
from django.shortcuts import render, redirect
from . import models  # we need to import models to get data from DB
# Create your views here.
from django.urls import reverse


def list(request):
    # the all_cars variable downloads all the objects from DB
    all_cars = models.Car.objects.all()
    context = {'all_cars': all_cars}
    return render(request, 'car_rental/list.html', context=context)


def add(request):
    if request.POST:
        # add the car
        brand = request.POST['brand']
        year = int(request.POST['year'])
        models.Car.objects.create(brand=brand, year=year)
        return redirect(reverse('car_rental:list'))
    else:
        return render(request, 'car_rental/add.html')


def delete(request):
    if request.POST:
        # delete the car
        pk = request.POST['pk']
        try:
            models.Car.objects.get(pk=pk).delete()
            return redirect(reverse('car_rental:list'))
        except:
            print("pk not found")
            return redirect(reverse('car_rental:list'))
    else:
        return render(request, 'car_rental/delete.html')

Django4Full-Stack course/DJANGO/section12/django_project/car_rental/templates/car_rental/add.html
{%extends "base.html"%} {%block content%}
<div class="container">
  <h1>ADD.HTML</h1>
  <h2>Add a new car to the database</h2>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="brand">Brand: </label>
      <input class="form-control" type="text" id="brand" name="brand" />
    </div>
    <div class="form-group">
      <label for="year">Year: </label>
      <input class="form-control" type="text" id="year" name="year" />
    </div>
    <br />

    <input class="btn btn-primary" type="submit" />
  </form>
</div>

{%endblock%}

Django4Full-Stack course/DJANGO/section12/django_project/car_rental/templates/car_rental/delete.html
{%extends "base.html"%} {%block content%}
<div class="container">
  <h1>DELETE.HTML</h1>
  <h1>Enter pk to delete car</h1>

  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="pk">PK Number: </label>
      <input class="form-control" type="text" id="pk" name="pk" />
    </div>
    <br />
    <input class="btn btn-primary" type="submit" />
  </form>
</div>
{%endblock%}

Django4Full-Stack course/DJANGO/section12/django_project/car_rental/templates/car_rental/list.html
{%extends "base.html"%} {%block content%}
<div class="container">
  <ul>
    {%for car in all_cars%}
    <li>{{car}}</li>
    {% endfor %}
  </ul>
</div>
<h1>LIST.HTML</h1>
{%endblock%}

Django4Full-Stack course/DJANGO/section12/django_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!--HTML BOOTSTRAP INSTALLING-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
    <title>My Website</title>
    <link rel="stylesheet" href="./style.css" />
    <link rel="icon" href="./favicon.ico" type="image/x-icon" />
    <!--JAVASCRIPT-->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <!--NAVBAR-->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{%url 'car_rental:list' %}">LIST</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'car_rental:add' %}">ADD</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'car_rental:delete' %}">DELETE</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!---->
    {%block content%} {% endblock %}
    <main></main>
    <script src="index.js"></script>
  </body>
</html>