Django4Full-Stack course/DJANGO/section14/school/classroom/urls.py
from django.urls import path
from .views import HomeView, TYView, ContactFormmView, TeacherCreateView, TeacherListView, TeacherDetailView, TeacherUpdateView, TeacherDeleteView

app_name = 'classroom'

urlpatterns = [
    path('',HomeView.as_view(), name='home'),
    path('thank_you/', TYView.as_view(), name='ty'),
    path('contact/', ContactFormmView.as_view(), name = 'contact'),
    path('create_teacher/', TeacherCreateView.as_view(), name = 'create_teacher'),
    path('teachers_list/',TeacherListView.as_view(), name = 'teachers_list'),
    path('teacher_detail/<int:pk>', TeacherDetailView.as_view(), name="teacher_details"),
    path('update_teacher/<int:pk>', TeacherUpdateView.as_view(), name="update_teacher"),
    path('delete_teacher/<int:pk>', TeacherDeleteView.as_view(), name="delete_teacher"),
]

Django4Full-Stack course/DJANGO/section14/school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/',include("classroom.urls")),
]

Django4Full-Stack course/DJANGO/section14/school/classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches {self.subject}"

Django4Full-Stack course/DJANGO/section14/school/classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

Django4Full-Stack course/DJANGO/section14/school/classroom/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView
from classroom.forms import ContactForm
from classroom.models import Teacher

# Create your views here.

class HomeView(TemplateView):
    template_name = 'classroom/home.html'

class TYView(TemplateView):
    template_name = "classroom/ty.html"

class TeacherCreateView(CreateView):
    model = Teacher 
    fields = "__all__"
    success_url = reverse_lazy('classroom:ty')
    def form_valid(self,form):
        print(form.cleaned_data)
        return super().form_valid(form)
    
class TeacherListView(ListView):
    model = Teacher 
    context_object_name = "teachers_list"
    queryset = Teacher.objects.all()

class TeacherDetailView(DetailView):
    model = Teacher

class TeacherUpdateView(UpdateView):
    model = Teacher 
    fields = "__all__"
    success_url = reverse_lazy("classroom:teachers_list")

class TeacherDeleteView(DeleteView):
    model = Teacher 
    success_url = reverse_lazy("classroom:ty")

class ContactFormmView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'
    success_url = reverse_lazy('classroom:ty')
    def form_valid(self,form):
        print(form.cleaned_data)
        return super().form_valid(form)

Django4Full-Stack course/DJANGO/section14/school/classroom/templates/classroom/contact.html
<h1>Form view template</h1>
<form method="POST">
  {% csrf_token %} {{form.as_p}}
  <input type="submit" value="Submit" />
</form>

Django4Full-Stack course/DJANGO/section14/school/classroom/templates/classroom/home.html
<h1>Welcome to home.html</h1>

<ul>
  <li>
    <a href="{% url 'classroom:ty' %}">Thank you page link</a>
  </li>
  <li>
    <a href="{% url 'classroom:contact' %}">Contact form page link</a>
  </li>
  <li>
    <a href="{% url 'classroom:create_teacher' %}"
      >Create new teacher page link</a
    >
  </li>
  <li>
    <a href="{% url 'classroom:teachers_list' %}">Teachers list page link</a>
  </li>
</ul>

Django4Full-Stack course/DJANGO/section14/school/classroom/templates/classroom/teacher_confirm_delete.html
<h1>Do you really want to delete {{teacher.first_name}}?</h1>
<form method="POST">
  {% csrf_token %} {{form.as_p}}
  <input type="submit" value="Confirm delete" />
</form>

Django4Full-Stack course/DJANGO/section14/school/classroom/templates/classroom/teacher_detail.html
<h1>Detail teacher view</h1>

{{teacher.pk}} - {{teacher.first_name}} {{teacher.last_name}} - subject:
{{teacher.subject}} <br />
<a href="/classroom/update_teacher/{{teacher.id}}"
  >Update the teacher information</a
>

<a href="/classroom/delete_teacher/{{teacher.id}}">Delete the teacher</a><br />

<a href="/classroom/">GO HOME</a>

Django4Full-Stack course/DJANGO/section14/school/classroom/templates/classroom/teacher_form.html
<h1>Add teacher form</h1>
<form method="POST">
  {% csrf_token %} {{form.as_p}}
  <input type="submit" value="Submit" />
</form>

Django4Full-Stack course/DJANGO/section14/school/classroom/templates/classroom/teacher_list.html
<h1>List teachers form</h1>
<ul>
  {% for teacher in teachers_list %}
  <li>
    <a href="/classroom/teacher_detail/{{teacher.id}}"
      >{{teacher.first_name}} {{teacher.last_name}} - {{teacher.subject}}</a
    >
  </li>
  {% endfor %}
</ul>

<br />
<a href="/classroom/">GO HOME</a>

Django4Full-Stack course/DJANGO/section14/school/classroom/templates/classroom/ty.html
<h1>Thank you!</h1>
<a href="/classroom/">GO HOME</a>